title: Supervisa Docs
description: Documentation for supervisa.io
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Full website: https://www.supervisa.io

logo: https://prenota-agent.s3.us-east-2.amazonaws.com/logo.png
favicon_ico: https://prenota-agent.s3.us-east-2.amazonaws.com/favicon.ico

color_scheme: blue